court/urls.py
from django.urls import path,  re_path
from .views import *
import supreme_court.settings as s

app_name='court'
urlpatterns=[
    path('', main,name='main'),
    re_path(r'(?P<pk>[0-9]+)_(?P<slug>[-a-zA-Zа-яA-Я0-9_]+)/$', detail,name='detail'),
    path('tags/<slug:tag_slug>/',arts_by_tag, name='arts_by_tag'),
    path('search_for=<str:keyword>', search, name='search'),
] 

supreme_court/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from . import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/',include('captcha.urls')),
    path ("", include ('court.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>',never_cache(serve)))
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

court/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import SlugField
from django.utils.text import slugify
from taggit.managers import TaggableManager
from .utilities import get_timestamp_path
from .templatetags.court_filters import cutDL
import supreme_court.settings as set


class AdmUser (AbstractUser):
    pass

class Articles (models.Model):
    title=models.CharField (max_length=300)
    author=models.ForeignKey(
        AdmUser,
        on_delete=models.CASCADE,
    )
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    image=models.ImageField(blank=True,upload_to="media/")
    slug=SlugField(max_length=300,blank=True,allow_unicode=True,unique=True)
    tags = TaggableManager(blank=True)
    
    def __str__(self):
        return self.title
       
    def slug_it(self):
        if not self.slug:
            self.slug=slugify(cutDL(self.title),allow_unicode=True)
            self.save(update_fields=['slug'])
        return self.slug

        class Meta:
            ordering=['-date']

class Comment (models.Model):
    art=models.ForeignKey(Articles,on_delete=models.CASCADE,verbose_name="Объявление")
    author=models.CharField(max_length=30, verbose_name="Автор")
    content=models.TextField(verbose_name="Содержание")
    is_active=models.BooleanField(default=True,db_index=True,verbose_name="Выводить на экран?")
    date=models.DateTimeField(auto_now_add=True,db_index=True,verbose_name="Опубликован")

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural="Комментарии"
        verbose_name="Комментарий"
        ordering=['date']

court/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

from .models import *


class GuestCommentForm(forms.ModelForm):
    captcha=CaptchaField(label="Введите текст с картинки")
    class Meta:
        model=Comment
        fields=('author','content','captcha',)

ins_validator=validators.RegexValidator(regex=r'\s{2,}',message="Поле не должно содержать больше двух пробелов", code='invalid_keyword',inverse_match=True)
class SearchForm(forms.Form):
    keyword=forms.CharField(required=False,max_length=20, label='Поиск по названию, содержанию, тегу',min_length=4,validators=[ins_validator])
    default_validators=[ins_validator]
    
    def run_my_validator (self, keyword):
        errors=[]
        try:
            ins_validator(keyword)
        except ValidationError:
            errors=[ins_validator.message]
            self.errors.update({ins_validator.code:ins_validator.message})
        return errors
    
    
              
        
        

court/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from taggit.models import Tag

from . import models
from .forms import  GuestCommentForm, SearchForm


def main (request):
    arts=models.Articles.objects.get_queryset().order_by('-date')
    paginator=Paginator(arts,7)
    if 'page' in request.GET:
        page_num=request.GET['page']
    else:
        page_num=1
    page=paginator.get_page(page_num)
    if 'keyword' in request.GET:
        keyword=request.GET['keyword']
        form=SearchForm(request.GET)
        errors=form.run_my_validator(keyword)
        if errors or keyword == '':
            messages.warning(request, 'Поле не должно содержать больше двух пробелов или быть пустым')
            return redirect('court:main')
        else:
            if form.is_valid():
                keyword=form.cleaned_data['keyword']
                return redirect ('court:search',keyword) 
    else:
        form=SearchForm()
    context={'arts':page.object_list,'page':page,'form':form }
    return render (request,"main.html",context)

def arts_by_tag(request,tag_slug=None):
    arts=models.Articles.objects.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        arts_by_tag=arts.filter(tags__in=[tag])
    context={'arts':arts_by_tag,'tag':tag}
    return render(request,'arts_by_tag.html',context)
    

def detail (request, pk, slug):
    art=models.Articles.objects.get(pk=pk)
    comments=models.Comment.objects.filter(art=pk,is_active=True)
    paginator=Paginator(comments,10,orphans=1)
    slug=slug
    if 'page' in request.GET:
        page_num=request.GET['page']
    else:
        page_num=1
    page=paginator.get_page(page_num)
    form_class=GuestCommentForm
    form=form_class()
    if request.method=="POST":
        c_form=form_class(request.POST)
        if c_form.is_valid():
            new_comment=c_form.save(commit=False)
            new_comment.art_id=pk
            new_comment.save()
            messages.add_message(request,messages.SUCCESS,'Комментарий добавлен')
            return HttpResponseRedirect(request.path)
        else:
            form=c_form
            messages.add_message(request,messages.WARNING,'Комментарий НЕ добавлен')   
    context={'art':art,'comments':page.object_list, 'form':form,'page':page}
    return render(request,'detail.html',context)

def search (request,keyword):
    keyword=keyword
    arts=models.Articles.objects.all()
    q=Q(title__icontains=keyword)|Q(body__icontains=keyword)|Q(tags__name__icontains=keyword)
    arts=arts.filter(q).distinct()
    paginator=Paginator(arts,7)
    if 'page' in request.GET:
        page_num=request.GET['page']
    else:
        page_num=1
    page=paginator.get_page(page_num)
    context={'page':page,'arts':page.object_list,'keyword':keyword}
    return render(request,'search.html',context)

templates/arts_by_tag.html
{% extends 'basic.html'%}


{% load static %}
{% load bootstrap4 %}
{% load court_filters %}
{% load thumbnail %}

{% block content %}
<h2 class="display-3 text-center font-fantasy">Новости, найденные по тегу "{{tag}}"
    <style>h2.display-3 {font-size:125%;}</style>
</h2>
         {% if arts %}
            <ul class="text-left font-times">
            {% for art in arts %}
                        <div class="media">
                            {% thumbnail art.image|default:'empty.png' 96x96 as photo %}  
                            <img class="img-thumbnail mt-1" src="{{photo.url}}" alt=''/>
                                <div class="media-body mt-1 ml-3 pl-3">
                                    <h3><a href="{% url 'court:detail' pk=art.pk slug=art.slug_it %}">               
                                        {{art.title|cutDL}}</a>
                                    </h3>
                                    <h6>{{art.body|cutDL|truncatewords:15}}</h6>
                                    <p class="font-italic">
                                        <style>
                                             p {font-size:75%;}
                                        </style>
                                        {{art.date}}
                                    </p>
                                </div>
                        </div>
            {% endfor %}
            &nbsp;&nbsp;
            &nbsp;&nbsp;
            </ul>
        {% endif %}
{% endblock %}
        

templates/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %} Главная {% endblock %} - Верховный Суд  </title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css'%}" media="all">
        {% bootstrap_javascript jquery="slim" %}
    </head>
    <body class="container-fluid no-gutters">
        <header class="mb-4">
            <h1 class="display-1 text-center font-fantasy">ВЕРХОВНЫЙ СУД</h1>
        </header>
        <div class="row no-gutters">
            <div class="col-2"></div>
            <div class="col-10">
                <nav class="navbar navbar-expand-lg">
                        <ul class="navbar-nav mr-auto">
                            <style>
                               ul.navbar-nav {flex-wrap: wrap;}
                            </style>
                            <a class="nav-link badge-info rounded font-weight-bold mr-2" id="upper-menu" href="{% url 'court:main' %}"> Главная  </a>
                            <a class="nav-link badge-secondary rounded" id="upper-menu" href="#"> Судебный департамент при Верховном Суде </a>
                            <a class="nav-link badge-dark rounded" id="upper-menu" href="#"> Суды общей юрисдикции  </a>
                            <a class="nav-link badge-secondary rounded" id="upper-menu" href="#"> Информация о закупках </a>
                            <a class="nav-link badge-dark rounded" id="upper-menu" href="#"> Профессиональный союз </a>
                            <a class="nav-link badge-secondary rounded" id="upper-menu" href="#"> Вызов в суд </a>
                            <a class="nav-link badge-dark rounded" id="upper-menu" href="#"> Законодательая инициатива  </a>
                            <a class="nav-link badge-secondary rounded" id="upper-menu" href="#"> Документы </a>
                        </ul>
                </nav>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-8"></div>
            <div class="col-4 mt-3"> 
                {% block search %}
                {% endblock %}
            </div>                     
        </div>
        <div class="row no-gutters margin-left:-15px и margin-right:-15px">
            <div class="col-2">
                <h5 class="main-menu">
                    <style>
                        h5.main-menu {font-style:normal;font-family:fantasy;color:rgb(7, 6, 6); font-size: 125%;}
                    </style>Главное меню
                </h5>
                <br>
                <nav class="nav-fill flex-fill font-weight-bold font-times">
                    <div class="dropdown dropright">
                        <a class="nav-link badge-dark rounded dropdown-toggle dropright" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Новости</a>
                            <div class="dropdown-menu dropright">
                                <a class="dropdown-item badge-dark rounded" href="#">Глава государства</a>
                                <a class="dropdown-item badge-secondary rounded" href="#">Документы</a>
                                <a class="dropdown-item badge-dark rounded" href="#">Информационное сообщение</a>
                                <a class="dropdown-item badge-secondary rounded" href="#">Министерство юстиции</a>
                                <a class="dropdown-item badge-dark rounded" href="#">Работа суда</a>
                                <a class="dropdown-item badge-secondary rounded" href="#">Официальное сообщение</a>
                                <a class="dropdown-item badge-dark rounded" href="#">Поздравления</a>
                                <a class="dropdown-item badge-secondary rounded" href="#">Общественная жизнь</a>
                                <a class="dropdown-item badge-dark rounded" href="#">СМИ</a>
                            </div>
                    </div>
                    <a class="nav-link badge-secondary rounded" href="#">Внепроцессуальные обращения к судьям</a>
                    <a class="nav-link badge-dark rounded" href="#">Временная экзаменационная комиссия</a>
                    <a class="nav-link badge-secondary rounded " href="#">Временная квалификационная коллегия судей</a>
                    <a class="nav-link badge-dark rounded" href="#">Пресс-служба</a>
                    <a class="nav-link badge-secondary rounded" href="#">Контакты</a>
                    <div class="dropdown dropright">
                        <a class="nav-link badge-dark rounded dropdown-toggle dropright" href="#"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Предотвращение <br> коррупции </a>
                            <div class="dropdown-menu dropright">
                                <a class="dropdown-item badge-dark rounded" href="#">Нормативно-правовые и иные акты в сфере противодействия коррупции</a>
                                <a class="dropdown-item badge-secondary rounded" href="#">Информационные материалы Верховного Суда в сфере противодействия коррупции</a>
                            </div>
                    </div>
                    <a class="nav-link badge-secondary rounded" href="#">Обращения в Верховный Суд</a>
                </nav>
            </div>
            <div class="col-9">
                <section class="border-0">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
                </section>
            </div>
            <div class="col-1">
               {% block social-media %}
               {% endblock %}
            </div>
        </div>
        <div class="row">
            <div>
                <footer class="footer">
                    <p class="text-left font-italic">Официальный сайт Верховного Суда Copyright &copy;</p> 
                </footer>
            </div>
        </div>
    </body>
</html>

templates/detail.html
{% extends 'basic.html' %}
{% load bootstrap4 %}
{% load court_filters %}

{% block title %}{{art.title}}{% endblock %}

{% block content %}
<div class ="container-fluid ml-3 mt-3">
    <div class="row justify-content-center">
        {% if art.image %}
        <div ><img src="{{art.image.url}}" class="img-fluid"></div>
        {% endif %}
        <div class="mt-3 ml-3 text-center">
            <h2 class="font-fantasy" >{{art.title|cutDL}}</h2>
            <p class="mt-5 text-justify font-weight-bold font-times">{{art.body|cutDL}}</p>
            <p class="font-italic text-left">
                <style>
                    p.font-italic {font-size:75%;}
                </style>
               Добавлено {{art.date}}
            </p>
        </div>
    </div>
</div>
<h4 class="mt-5 mb-5 pb-5 ml-3">Новый комментарий</h4>
    <form method="post" class="ml-3">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons %}
            <button class= "ml-5  mb-5" type='submit'>Добавить</button> 
        {% endbuttons %}
    </form>
{% if comments %}
<div class="mt-5 ml-3">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{comment.author}}</h5>
        <p>{{comment.content}}</p>
        <p class="text-left font-italic">{{comment.date}}</p>
    </div>
    {% endfor %}
</div>
<div class="mb-5 pb-5">
    {% if page.has_previous %}
    <a href="?page={{page.previous_page_number}}">&lt;</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    {% endif %}
    Часть № {{page.number}} из {{page.paginator.num_pages}}
    {% if page.has_next %}
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="?page={{page.next_page_number}}">&gt;</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}

templates/main.html
{% extends 'basic.html'%}


{% load static %}
{% load bootstrap4 %}
{% load court_filters %}
{% load thumbnail %}

{% block search %}
<form required minlength="4">
    <div class="row form-group">
        <div class="col-9">
            {% bootstrap_form form=form show_label=False alert_error_type='all' %} 
        </div>
        <div class="col-3">{% bootstrap_button content='Искать' button_type='submit' %}</div> 
    </div>
</form>
{% endblock%}
{% block content %}
    <h2 class="my-header">Последние новости</h2>
        {% if arts %}
            <ul class="text-left">
            {% for art in arts %}
                        <div class="media">
                            {% thumbnail art.image|default:'empty.png' 96x96 as photo %}  
                            <img class="img-thumbnail mt-1" src="{{photo.url}}" alt=''/>
                                <div class="media-body mt-1 ml-3 pl-3">
                                    <h3><a href="{% url 'court:detail' pk=art.pk slug=art.slug_it %}" class="font-times">               
                                        {{art.title|cutDL}}</a>
                                    </h3>
                                    <h6 class='font-times'>{{art.body|cutDL|truncatewords:15}}</h6>
                                    {% if art.tags.exists %}
                                    <p>
                                       Теги:
                                            {% for tag in art.tags.all %}
                                            <a href="{% url 'court:arts_by_tag' tag.slug %}" class="badge badge-success font-bold">
                                                <style>
                                                    a.badge {font-size:125%;}
                                                </style>
                                            {{ tag.name }}
                                            </a>
                                            {% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                    {% endif %}
                                    </p>
                                    <div class='row'>
                                        <div class='col-3'>
                                            <p class="font-italic">
                                                <style>
                                                    p {font-size:85%;}
                                               </style>
                                                {{art.date}}
                                            </p>
                                        </div>
                                        <div class='col-9'>
                                            <p class="font-italic">
                                                {% if art.comment_set.count %}
                                                    {{art.comment_set.count|comment_filter}}
                                                {% endif %}
                                            </p>
                                        </div>                                  
                                </div>
                                </div>
                        </div>
            {% endfor %}
            &nbsp;&nbsp;
            &nbsp;&nbsp;
            </ul>
            <div class="mb-5 pb-5">
                {% if page.has_previous %}
                <a href="?page={{page.previous_page_number}}">&lt;</a>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                {% endif %}
                Часть № {{page.number}} из {{page.paginator.num_pages}}
                {% if page.has_next %}
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <a href="?page={{page.next_page_number}}">&gt;</a>
                {% endif %}
            </div>
        {% endif %}
{% endblock %}
{% block social-media %}
<h5 class="main-menu mt-3"> Ссылки <br> на наши <br> ресурсы </h5>
    <p><a href="https://vk.com/club65375199"><img src="{% static 'img/vk.png' %}" alt="Мы ВКонтакте" width="50" height="50"></a></p> 
    <p><a href="https://www.youtube.com/channel/UCrOjOxPktsUunlrS6jRmPkg"><img src="{% static 'img/yt.jpg' %}" alt="Наш канал на YouTube" width="50" height="50"></a></p> 
{% endblock %}

templates/search.html
{% extends 'basic.html'%}


{% load static %}
{% load bootstrap4 %}
{% load court_filters %}
{% load thumbnail %}

{% block content %}
    {% if arts %}
        <h4 class="display-3 text-center h-75 font-fantasy">Найдены следующие новости по ключевому слову "{{keyword}}"</h4>
            <ul class="text-left font-times">
            {% for art in arts %}
                        <div class="media">
                            {% thumbnail art.image|default:'empty.png' 96x96 as photo %}  
                            <img class="img-thumbnail mt-1" src="{{photo.url}}" alt=''/>
                                <div class="media-body mt-1 ml-3 pl-3">
                                    <h3><a href="{% url 'court:detail' pk=art.pk slug=art.slug_it %}">               
                                        {{art.title|cutDL}}</a>
                                    </h3>
                                    <h6>{{art.body|cutDL|truncatewords:15}}</h6>
                                    <p class="font-italic">
                                        <style>
                                             p {font-size:75%;}
                                        </style>
                                        {{art.date}}
                                    </p>
                                </div>
                        </div>
            {% endfor %}  
            &nbsp;&nbsp;
            &nbsp;&nbsp;
            </ul>
            <div class="mb-5 pb-5">
                {% if page.has_previous %}
                <a href="?page={{page.previous_page_number}}">&lt;</a>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                {% endif %}
                Часть № {{page.number}} из {{page.paginator.num_pages}}
                {% if page.has_next %}
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <a href="?page={{page.next_page_number}}">&gt;</a>
                {% endif %}
    {% else %}
        <h4 class="text-center">К сожалению, по Вашему запросу ничего не найдено</h2>
            &nbsp;&nbsp;
            &nbsp;&nbsp; 
    {% endif %}
{% endblock %}